name: edge_cloudflare_example
description: An example Cloudflare Worker written in Dart.
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge_cloudflare: 0.0.4+4
  edge_dart: ^0.0.3