name: edge_dart
description: edge_dart library for make your program dart more easy.
version: 0.0.0
repository: https://github.com/azkadev/edge.git
issue_tracker: https://github.com/azkadev/edge.git
homepage: https://youtube.com/@azkadev


executables:
  edge_dart: edge_dart
  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  general_lib: ^0.0.4
  mason_logger: ^0.2.10
  path: ^1.8.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  msix: ^3.12.1
  packagex: ^0.0.28
  test: ^1.24.2

msix_config: 
  display_name: edge_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.edge_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: edge_dart
  dart_target: edge_dart
  flutter_target: main
  dart_name: edge_dart
  flutter_name: edge_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
