name: edge_netlify_example
description: A Netlify Edge function written in Dart.
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge_netlify: 0.0.1-dev.14
  edge_dart: ^0.0.3