# melos_managed_dependency_overrides: edge_netlify,edge,edge_dart_runtime
dependency_overrides:
  edge_dart:
    path: ../../edge_dart
  edge_dart_runtime:
    path: ../../edge_dart_runtime
  edge_netlify:
    path: ..
