name: edge_dart_runtime
description: A Edge runtime dart.
homepage: https://github.com/azkadev
repository: https://github.com/azkadev/edge
version: 0.0.1

environment:
  sdk: ">3.1.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  js: ^0.6.7
  typings: ^0.0.4

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http: ^1.1.0
