name: supabase_edge_functions_template
description: A Supaabase Edge Functions example written in Dart.
version: 0.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.7
  edge_http_client: ^0.0.1+3
  general_lib: ^0.0.31
  supabase: ^1.11.11
  supabase_client: ^0.0.25
  supabase_functions: ^0.0.1
  telegram_client_edge: ^0.0.1

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  http: ^1.1.0