name: edge_supabase
description: Write and deploy Dart functions to Supabase Functions.
homepage: https://github.com/azkadev
repository: https://github.com/azkadev/edge
version: 0.0.0

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  edge_deno_deploy: ^0.0.0
  edge_dart: ^0.0.3
  edge_dart_runtime: ^0.0.0
  js: ^0.6.7
  typings: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
