name: edge
description: A library edge.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev

executables:
  edge: edge

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:  
  ffi: ^2.0.2
  general_lib: ^0.0.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  packagex: ^0.0.28
