name: edge_netlify
description: Write and deploy Dart functions to the Netlify Edge network.
homepage: https://github.com/azkadev
repository: https://github.com/azkadev/edge
version: 0.0.0

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  edge_dart: ^0.0.7
  edge_dart_runtime: ^0.0.4+2
  js: ^0.6.7
  path: ^1.8.3
  typings: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
