name: vercel_edge_example
description: An Vercel Edge function written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.1
  vercel_edge: ^0.0.1
  {{#shelf}}
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  {{/shelf}}

dev_dependencies:
  lints: ^2.0.1 