name: edge_example
description: A basic example of using the edge package.
homepage: https://github.com/azkadev
repository: https://github.com/azkadev/edge
version: 0.0.11+1
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.7
  edge_dart_runtime: ^0.0.1